/**
 * Quran Model - Salifz
 * Static Quran data structure
 */

const mongoose = require('mongoose');

const ayahSchema = new mongoose.Schema({
  number: { type: Number, required: true },
  numberInSurah: { type: Number, required: true },
  text: { type: String, required: true },
  textUthmani: String,
  juz: { type: Number, required: true },
  manzil: Number,
  page: Number,
  ruku: Number,
  hizbQuarter: Number,
  sajda: { type: Boolean, default: false }
}, { _id: false });

const surahSchema = new mongoose.Schema({
  number: { type: Number, required: true, unique: true },
  name: { type: String, required: true },
  englishName: { type: String, required: true },
  englishNameTranslation: String,
  numberOfAyahs: { type: Number, required: true },
  revelationType: { type: String, enum: ['Meccan', 'Medinan'] },
  juzStart: Number,
  juzEnd: Number,
  ayahs: [ayahSchema]
}, { timestamps: true });

const Surah = mongoose.model('Surah', surahSchema);

// Surah metadata (for quick reference)
const SURAH_DATA = [
  { number: 1, name: 'الفاتحة', englishName: 'Al-Fatiha', ayahs: 7, type: 'Meccan' },
  { number: 2, name: 'البقرة', englishName: 'Al-Baqara', ayahs: 286, type: 'Medinan' },
  { number: 3, name: 'آل عمران', englishName: 'Aal-Imran', ayahs: 200, type: 'Medinan' },
  { number: 4, name: 'النساء', englishName: 'An-Nisa', ayahs: 176, type: 'Medinan' },
  { number: 5, name: 'المائدة', englishName: 'Al-Maida', ayahs: 120, type: 'Medinan' },
  { number: 6, name: 'الأنعام', englishName: 'Al-Anam', ayahs: 165, type: 'Meccan' },
  { number: 7, name: 'الأعراف', englishName: 'Al-Araf', ayahs: 206, type: 'Meccan' },
  { number: 8, name: 'الأنفال', englishName: 'Al-Anfal', ayahs: 75, type: 'Medinan' },
  { number: 9, name: 'التوبة', englishName: 'At-Tawba', ayahs: 129, type: 'Medinan' },
  { number: 10, name: 'يونس', englishName: 'Yunus', ayahs: 109, type: 'Meccan' },
  { number: 11, name: 'هود', englishName: 'Hud', ayahs: 123, type: 'Meccan' },
  { number: 12, name: 'يوسف', englishName: 'Yusuf', ayahs: 111, type: 'Meccan' },
  { number: 13, name: 'الرعد', englishName: 'Ar-Ra\'d', ayahs: 43, type: 'Medinan' },
  { number: 14, name: 'إبراهيم', englishName: 'Ibrahim', ayahs: 52, type: 'Meccan' },
  { number: 15, name: 'الحجر', englishName: 'Al-Hijr', ayahs: 99, type: 'Meccan' },
  { number: 16, name: 'النحل', englishName: 'An-Nahl', ayahs: 128, type: 'Meccan' },
  { number: 17, name: 'الإسراء', englishName: 'Al-Isra', ayahs: 111, type: 'Meccan' },
  { number: 18, name: 'الكهف', englishName: 'Al-Kahf', ayahs: 110, type: 'Meccan' },
  { number: 19, name: 'مريم', englishName: 'Maryam', ayahs: 98, type: 'Meccan' },
  { number: 20, name: 'طه', englishName: 'Ta-Ha', ayahs: 135, type: 'Meccan' },
  { number: 21, name: 'الأنبياء', englishName: 'Al-Anbiya', ayahs: 112, type: 'Meccan' },
  { number: 22, name: 'الحج', englishName: 'Al-Hajj', ayahs: 78, type: 'Medinan' },
  { number: 23, name: 'المؤمنون', englishName: 'Al-Muminun', ayahs: 118, type: 'Meccan' },
  { number: 24, name: 'النور', englishName: 'An-Nur', ayahs: 64, type: 'Medinan' },
  { number: 25, name: 'الفرقان', englishName: 'Al-Furqan', ayahs: 77, type: 'Meccan' },
  { number: 26, name: 'الشعراء', englishName: 'Ash-Shuara', ayahs: 227, type: 'Meccan' },
  { number: 27, name: 'النمل', englishName: 'An-Naml', ayahs: 93, type: 'Meccan' },
  { number: 28, name: 'القصص', englishName: 'Al-Qasas', ayahs: 88, type: 'Meccan' },
  { number: 29, name: 'العنكبوت', englishName: 'Al-Ankabut', ayahs: 69, type: 'Meccan' },
  { number: 30, name: 'الروم', englishName: 'Ar-Rum', ayahs: 60, type: 'Meccan' },
  { number: 31, name: 'لقمان', englishName: 'Luqman', ayahs: 34, type: 'Meccan' },
  { number: 32, name: 'السجدة', englishName: 'As-Sajda', ayahs: 30, type: 'Meccan' },
  { number: 33, name: 'الأحزاب', englishName: 'Al-Ahzab', ayahs: 73, type: 'Medinan' },
  { number: 34, name: 'سبإ', englishName: 'Saba', ayahs: 54, type: 'Meccan' },
  { number: 35, name: 'فاطر', englishName: 'Fatir', ayahs: 45, type: 'Meccan' },
  { number: 36, name: 'يس', englishName: 'Ya-Sin', ayahs: 83, type: 'Meccan' },
  { number: 37, name: 'الصافات', englishName: 'As-Saffat', ayahs: 182, type: 'Meccan' },
  { number: 38, name: 'ص', englishName: 'Sad', ayahs: 88, type: 'Meccan' },
  { number: 39, name: 'الزمر', englishName: 'Az-Zumar', ayahs: 75, type: 'Meccan' },
  { number: 40, name: 'غافر', englishName: 'Ghafir', ayahs: 85, type: 'Meccan' },
  { number: 41, name: 'فصلت', englishName: 'Fussilat', ayahs: 54, type: 'Meccan' },
  { number: 42, name: 'الشورى', englishName: 'Ash-Shura', ayahs: 53, type: 'Meccan' },
  { number: 43, name: 'الزخرف', englishName: 'Az-Zukhruf', ayahs: 89, type: 'Meccan' },
  { number: 44, name: 'الدخان', englishName: 'Ad-Dukhan', ayahs: 59, type: 'Meccan' },
  { number: 45, name: 'الجاثية', englishName: 'Al-Jathiya', ayahs: 37, type: 'Meccan' },
  { number: 46, name: 'الأحقاف', englishName: 'Al-Ahqaf', ayahs: 35, type: 'Meccan' },
  { number: 47, name: 'محمد', englishName: 'Muhammad', ayahs: 38, type: 'Medinan' },
  { number: 48, name: 'الفتح', englishName: 'Al-Fath', ayahs: 29, type: 'Medinan' },
  { number: 49, name: 'الحجرات', englishName: 'Al-Hujurat', ayahs: 18, type: 'Medinan' },
  { number: 50, name: 'ق', englishName: 'Qaf', ayahs: 45, type: 'Meccan' },
  { number: 51, name: 'الذاريات', englishName: 'Adh-Dhariyat', ayahs: 60, type: 'Meccan' },
  { number: 52, name: 'الطور', englishName: 'At-Tur', ayahs: 49, type: 'Meccan' },
  { number: 53, name: 'النجم', englishName: 'An-Najm', ayahs: 62, type: 'Meccan' },
  { number: 54, name: 'القمر', englishName: 'Al-Qamar', ayahs: 55, type: 'Meccan' },
  { number: 55, name: 'الرحمن', englishName: 'Ar-Rahman', ayahs: 78, type: 'Medinan' },
  { number: 56, name: 'الواقعة', englishName: 'Al-Waqia', ayahs: 96, type: 'Meccan' },
  { number: 57, name: 'الحديد', englishName: 'Al-Hadid', ayahs: 29, type: 'Medinan' },
  { number: 58, name: 'المجادلة', englishName: 'Al-Mujadila', ayahs: 22, type: 'Medinan' },
  { number: 59, name: 'الحشر', englishName: 'Al-Hashr', ayahs: 24, type: 'Medinan' },
  { number: 60, name: 'الممتحنة', englishName: 'Al-Mumtahina', ayahs: 13, type: 'Medinan' },
  { number: 61, name: 'الصف', englishName: 'As-Saff', ayahs: 14, type: 'Medinan' },
  { number: 62, name: 'الجمعة', englishName: 'Al-Jumua', ayahs: 11, type: 'Medinan' },
  { number: 63, name: 'المنافقون', englishName: 'Al-Munafiqun', ayahs: 11, type: 'Medinan' },
  { number: 64, name: 'التغابن', englishName: 'At-Taghabun', ayahs: 18, type: 'Medinan' },
  { number: 65, name: 'الطلاق', englishName: 'At-Talaq', ayahs: 12, type: 'Medinan' },
  { number: 66, name: 'التحريم', englishName: 'At-Tahrim', ayahs: 12, type: 'Medinan' },
  { number: 67, name: 'الملك', englishName: 'Al-Mulk', ayahs: 30, type: 'Meccan' },
  { number: 68, name: 'القلم', englishName: 'Al-Qalam', ayahs: 52, type: 'Meccan' },
  { number: 69, name: 'الحاقة', englishName: 'Al-Haqqah', ayahs: 52, type: 'Meccan' },
  { number: 70, name: 'المعارج', englishName: 'Al-Maarij', ayahs: 44, type: 'Meccan' },
  { number: 71, name: 'نوح', englishName: 'Nuh', ayahs: 28, type: 'Meccan' },
  { number: 72, name: 'الجن', englishName: 'Al-Jinn', ayahs: 28, type: 'Meccan' },
  { number: 73, name: 'المزمل', englishName: 'Al-Muzzammil', ayahs: 20, type: 'Meccan' },
  { number: 74, name: 'المدثر', englishName: 'Al-Muddaththir', ayahs: 56, type: 'Meccan' },
  { number: 75, name: 'القيامة', englishName: 'Al-Qiyama', ayahs: 40, type: 'Meccan' },
  { number: 76, name: 'الإنسان', englishName: 'Al-Insan', ayahs: 31, type: 'Medinan' },
  { number: 77, name: 'المرسلات', englishName: 'Al-Mursalat', ayahs: 50, type: 'Meccan' },
  { number: 78, name: 'النبإ', englishName: 'An-Naba', ayahs: 40, type: 'Meccan' },
  { number: 79, name: 'النازعات', englishName: 'An-Naziat', ayahs: 46, type: 'Meccan' },
  { number: 80, name: 'عبس', englishName: 'Abasa', ayahs: 42, type: 'Meccan' },
  { number: 81, name: 'التكوير', englishName: 'At-Takwir', ayahs: 29, type: 'Meccan' },
  { number: 82, name: 'الانفطار', englishName: 'Al-Infitar', ayahs: 19, type: 'Meccan' },
  { number: 83, name: 'المطففين', englishName: 'Al-Mutaffifin', ayahs: 36, type: 'Meccan' },
  { number: 84, name: 'الانشقاق', englishName: 'Al-Inshiqaq', ayahs: 25, type: 'Meccan' },
  { number: 85, name: 'البروج', englishName: 'Al-Buruj', ayahs: 22, type: 'Meccan' },
  { number: 86, name: 'الطارق', englishName: 'At-Tariq', ayahs: 17, type: 'Meccan' },
  { number: 87, name: 'الأعلى', englishName: 'Al-Ala', ayahs: 19, type: 'Meccan' },
  { number: 88, name: 'الغاشية', englishName: 'Al-Ghashiya', ayahs: 26, type: 'Meccan' },
  { number: 89, name: 'الفجر', englishName: 'Al-Fajr', ayahs: 30, type: 'Meccan' },
  { number: 90, name: 'البلد', englishName: 'Al-Balad', ayahs: 20, type: 'Meccan' },
  { number: 91, name: 'الشمس', englishName: 'Ash-Shams', ayahs: 15, type: 'Meccan' },
  { number: 92, name: 'الليل', englishName: 'Al-Layl', ayahs: 21, type: 'Meccan' },
  { number: 93, name: 'الضحى', englishName: 'Ad-Duha', ayahs: 11, type: 'Meccan' },
  { number: 94, name: 'الشرح', englishName: 'Ash-Sharh', ayahs: 8, type: 'Meccan' },
  { number: 95, name: 'التين', englishName: 'At-Tin', ayahs: 8, type: 'Meccan' },
  { number: 96, name: 'العلق', englishName: 'Al-Alaq', ayahs: 19, type: 'Meccan' },
  { number: 97, name: 'القدر', englishName: 'Al-Qadr', ayahs: 5, type: 'Meccan' },
  { number: 98, name: 'البينة', englishName: 'Al-Bayyina', ayahs: 8, type: 'Medinan' },
  { number: 99, name: 'الزلزلة', englishName: 'Az-Zalzala', ayahs: 8, type: 'Medinan' },
  { number: 100, name: 'العاديات', englishName: 'Al-Adiyat', ayahs: 11, type: 'Meccan' },
  { number: 101, name: 'القارعة', englishName: 'Al-Qaria', ayahs: 11, type: 'Meccan' },
  { number: 102, name: 'التكاثر', englishName: 'At-Takathur', ayahs: 8, type: 'Meccan' },
  { number: 103, name: 'العصر', englishName: 'Al-Asr', ayahs: 3, type: 'Meccan' },
  { number: 104, name: 'الهمزة', englishName: 'Al-Humaza', ayahs: 9, type: 'Meccan' },
  { number: 105, name: 'الفيل', englishName: 'Al-Fil', ayahs: 5, type: 'Meccan' },
  { number: 106, name: 'قريش', englishName: 'Quraish', ayahs: 4, type: 'Meccan' },
  { number: 107, name: 'الماعون', englishName: 'Al-Maun', ayahs: 7, type: 'Meccan' },
  { number: 108, name: 'الكوثر', englishName: 'Al-Kawthar', ayahs: 3, type: 'Meccan' },
  { number: 109, name: 'الكافرون', englishName: 'Al-Kafirun', ayahs: 6, type: 'Meccan' },
  { number: 110, name: 'النصر', englishName: 'An-Nasr', ayahs: 3, type: 'Medinan' },
  { number: 111, name: 'المسد', englishName: 'Al-Masad', ayahs: 5, type: 'Meccan' },
  { number: 112, name: 'الإخلاص', englishName: 'Al-Ikhlas', ayahs: 4, type: 'Meccan' },
  { number: 113, name: 'الفلق', englishName: 'Al-Falaq', ayahs: 5, type: 'Meccan' },
  { number: 114, name: 'الناس', englishName: 'An-Nas', ayahs: 6, type: 'Meccan' }
];

// Total ayahs in Quran: 6236
const TOTAL_AYAHS = SURAH_DATA.reduce((sum, s) => sum + s.ayahs, 0);

module.exports = { Surah, SURAH_DATA, TOTAL_AYAHS };
